#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

# Check if less than 3 parameters are passed
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
ip=$2
username=$3
ssh_key=$4

# Transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$ip":~/ || exit 1
