#!/usr/bin/env bash
# This script installs and configures Nginx web server

# Install nginx
apt-get update
apt-get install -y nginx

# Ensure nginx is listening on port 80
sed -i '/listen 80 default_server;/c\listen 80;' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# Create a page containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html
