#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Create a custom 404 page
echo '<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n\'est pas une page</p>
</body>
</html>
' > /usr/share/nginx/html/404.html

# Create a configuration file for handling 404 errors
echo '
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}
' > /etc/nginx/sites-available/404_error

# Create a symbolic link to enable the site configuration
ln -sf /etc/nginx/sites-available/404_error /etc/nginx/sites-enabled/

# Remove the default configuration
rm -f /etc/nginx/sites-enabled/default

# Reload Nginx to apply changes
service nginx reload
