#!/usr/bin/env bash

# 2. MAC and IP address
Questions:

What is a MAC address?

The unique identifier of a network interface [5].
What is an IP address?

Is to devices connected to a network what postal address is to houses [6]

